#!/usr/bin/env python3
"""Checks that every UI string has a Russian translation and generates UI/Loc.Ru.cs from tools/ru.json."""
import glob, json, os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.join(HERE, "..", "src", "HoodieCompanion")
ru = json.load(open(os.path.join(HERE, "ru.json"), encoding="utf-8"))
keys = []
for f in glob.glob(os.path.join(APP, "**", "*.cs"), recursive=True):
    if "/bin/" in f or "/obj/" in f or f.endswith("Loc.Ru.cs"):
        continue
    s = open(f, encoding="utf-8").read()
    for m in re.finditer(r'\b(?:L\.)?(?:T|F)\(\s*("(?:[^"\\]|\\.)*")', s):
        k = eval(m.group(1))
        if k not in keys:
            keys.append(k)
    for m in re.finditer(r'\(PresenceMode\.\w+, ("(?:[^"\\]|\\.)*")\)', s):
        k = eval(m.group(1))
        if k not in keys:
            keys.append(k)
missing = [k for k in keys if k not in ru]
def cs(x):
    return '"' + x.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'
out = ["// <auto-generated> by tools/gen_loc.py from tools/ru.json. Do not edit by hand. </auto-generated>",
       "using System.Collections.Generic;", "", "namespace HoodieCompanion.UI;", "", "public static partial class L", "{",
       "    private static readonly Dictionary<string, string> Ru = new()", "    {"]
for k, v in ru.items():
    out.append(f"        [{cs(k)}] = {cs(v)},")
out += ["    };", "}", ""]
open(os.path.join(APP, "UI", "Loc.Ru.cs"), "w", encoding="utf-8").write("\n".join(out))
print(f"{len(keys)} strings, {len(ru)} translations, missing: {missing}")
sys.exit(1 if missing else 0)
